assets:
  - id: cli-tools
    installer: cargo-binstall
    packages: [eza, lsd, fd-find, ripgrep, bingrep, hx, just, sd, procs, du-dust, gping, tree-sitter-cli, macchina, multibg-wayland, bottom, broot]
