assets:
  - id: desktop-apps
    remote: flathub
    refs:
      - io.gitlab.librewolf-community
      - com.google.Chrome
      - com.brave.Browser
      - app.zen_browser.zen
      - dev.zed.Zed
      - org.telegram.desktop
      - com.discordapp.Discord
      - org.zulip.Zulip
      - dev.vencord.Vesktop
      - com.spotify.Client
      - org.audacityteam.Audacity
      - org.kde.audiotube
      - io.github.hrkfdn.ncspot
      - org.gnome.Decibels
      - io.bassi.Amberol
      - com.github.neithern.g4music
      - org.kde.kdenlive
      - org.inkscape.Inkscape
      - org.kde.krita
      - org.blender.Blender
      - org.freecad.FreeCAD
      - org.godotengine.Godot
      - org.librecad.librecad
      - com.bambulab.BambuStudio
      - io.gitlab.liferooter.TextPieces
      - org.gnome.gitlab.somas.Apostrophe
      - org.gnome.gitlab.ilhooq.Bookup
      - io.github.diegopvlk.Dosage
      - page.codeberg.censor.Censor
      - com.logseq.Logseq
      - app.devsuite.Ptyxis
      - org.wezfurlong.wezterm
      - com.mattjakeman.ExtensionManager
      - com.github.tchx84.Flatseal
      - io.github.giantpinkrobots.flatsweep
      - io.github.flattool.Warehouse
      - net.nokyan.Resources
      - page.tesk.Refine
      - io.missioncenter.MissionCenter
      - be.alexandervanhee.gradia
      - io.github.mrvladus.List
      - com.belmoussaoui.Authenticator
      - org.gnome.Polari
      - org.gnome.dspy
      - io.github.swordpuffin.rewaita
      - org.gnome.design.Emblem
      - org.mozilla.vpn
      - io.github.zingytomato.netpeek
      - com.oguzhaninan.Stacer
      - com.pojtinger.felicitas.Sessions
      - com.rafaelmardojai.Blanket
      - io.github.nozwock.Packet
      - org.localsend.localsend_app
      - rest.insomnia.Insomnia
      - com.vscodium.codium
      - io.gitlab.news_flash.NewsFlash
      - dev.Cogitri.Health
      - io.github.nokse22.Exhibit
  - id: obs-studio
    remote: flathub
    refs:
      - com.obsproject.Studio
      - com.obsproject.Studio.Plugin.DroidCam
      - com.obsproject.Studio.Plugin.BackgroundRemoval
      - com.obsproject.Studio.Plugin.Gstreamer
      - com.obsproject.Studio.Plugin.GStreamerVaapi
      - com.obsproject.Studio.Plugin.OBSPWVideo
      - com.obsproject.Studio.Plugin.AitumMultistream
      - com.obsproject.Studio.Plugin.SceneSwitcher
      - com.obsproject.Studio.Plugin.CompositeBlur
      - com.obsproject.Studio.Plugin.AdvancedMasks
      - com.obsproject.Studio.Plugin._3DEffect
      - com.obsproject.Studio.Plugin.Shaderfilter
      - com.obsproject.Studio.Plugin.TransitionTable
