name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c  # v6.4.0
        with:
          go-version-file: go.mod
      - run: sudo apt update && sudo apt install -y just npm yamllint shellcheck shfmt
      - run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - run: npm install -g prettier prettier-plugin-sh yaml-language-server
      - run: test -z "$(gofmt -l .)"
      - run: just --fmt --check --unstable
      - run: yamlfmt -lint .
      - run: prettier --check "**/*.{md,json,jsonc}" --ignore-path .prettierignore
      - run: yamllint .
      - run: go vet ./...
      - run: go test ./...
      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee  # v1.0.4
      - run: actionlint
      - run: go build -o bin/uboot ./cmd/uboot
      - run: ./bin/uboot --list
      - run: ./bin/uboot --config ./configs --validate
      - run: ./bin/uboot --config ./configs --all --dry-run
